[tox]
envlist = py{312}-django60
          py312-django60

[testenv]
setenv =
    PYTHONDONTWRITEBYTECODE=1
deps =
    -rrequirements/requirements-testing.txt
    coverage
    django60: Django>=6.0,<6.1
commands = ./runtests.py {posargs}
allowlist_externals = *
